name: Check Image Build

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ "release/**", "develop" ]
    paths-ignore:
      - '.github/**'

jobs:
  frontend:
    name: Check Standalone Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: docker build . --file services/frontend/Dockerfile --tag justnz/alertflow:frontend-test

      - name: Run Frontend Docker Image
        run: docker run --rm justnz/alertflow:frontend-test
  backend:
    name: Check Standalone Backend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: docker build . --file services/backend/Dockerfile --tag justnz/alertflow:backend-test

      - name: Run Backend Docker Image
        run: docker run --rm justnz/alertflow:backend-test
  alertflow:
    name: Check AlertFlow Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build AlertFlow Docker Image
        run: docker build . --file Dockerfile --tag justnz/alertflow:test

      - name: Run AlertFlow Docker Image
        run: docker run --rm justnz/alertflow:test
