name: Check Image Build

on:
  pull_request:
    types: [opened, reopened]
    branches: [ "release/**", "develop" ]
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Check Build
    runs-on: [self-hosted, alertflow]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag harbor.justlab.xyz/alertflow/frontend:test
