name: Build & Push Docker Image Main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Push
    runs-on: [self-hosted, alertflow]
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag alertflow/frontend:latest --tag harbor.justlab.xyz/alertflow/frontend:latest --tag harbor.justlab.xyz/alertflow/frontend:${{ github.ref_name }}

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          registry: harbor.justlab.xyz
          username: ${{ secrets.HARBOR_LOGIN_USERNAME }}
          password: ${{ secrets.HARBOR_LOGIN_PASSWORD }}
          logout: false
      
      - name: Push latest image
        run: docker push harbor.justlab.xyz/alertflow/frontend:latest

      - name: Push branch image
        run: docker push harbor.justlab.xyz/alertflow/frontend:${{ github.ref_name }}    
