name: Build & Push Docker Image Develop

on:
  push:
    branches: [ "develop" ]
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Build & Push
    runs-on: [self-hosted, alertflow]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag harbor.justlab.xyz/alertflow/frontend:${{ github.ref_name }}

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          registry: harbor.justlab.xyz
          username: ${{ secrets.HARBOR_LOGIN_USERNAME }}
          password: ${{ secrets.HARBOR_LOGIN_PASSWORD }}
          logout: false

      - name: Push Branch Image
        run: docker push harbor.justlab.xyz/alertflow/frontend:${{ github.ref_name }}    
