name: Release Version

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: [self-hosted, alertflow]
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
