name: Release Version

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: [self-hosted, alertflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          branch: develop
          base: main
          title: "Automatically created PR from develop to main!"
  
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag harbor.justlab.xyz/alertflow/frontend:${{ github.ref_name }}
  
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: harbor.justlab.xyz
          username: ${{ secrets.HARBOR_LOGIN_USERNAME }}
          password: ${{ secrets.HARBOR_LOGIN_PASSWORD }}
  
      - name: Push Docker Image
        run: docker push harbor.justlab.xyz/alertflow/frontend:${{ github.ref_name }}
